# 基础镜像
FROM eclipse-temurin:17-jdk-alpine
# 作者
MAINTAINER 68

# 配置
ENV PARAMS=""

# 时区
ENV TZ=PRC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 添加应用
ADD target/ai-mcp-knowledge-app.jar /ai-mcp-knowledge-app.jar

ENTRYPOINT ["sh","-c","java -jar $JAVA_OPTS /ai-mcp-knowledge-app.jar $PARAMS"]
